### ISSUE TITLE
Daily goal bar is exceeding 100% limit.

### ISSUE THREAD

**Issue by yogirajbshinde21** [aradzie/keybr.com#265] opened 2024-08-10 11:51 UTC
As we can see in this image, daily goal is exceeding in this bar.
Rather than exceeding, it should show something like "Goal Completed", so that the user will be acknowledged that they have completed his Daily Target.

![Screenshot 2024-08-10 171925](https://github.com/user-attachments/assets/e01ad8c3-5f6d-49f4-ac0c-a528f0b1b698)

**Comment by burhanharoon** [comment] 2024-08-16 11:00
@aradzie That sounds like a great idea. I have faced this issue several times, and I think a completion message instead of 105% would be better. I can make the PR. WDYT?

**Comment by ColdCactus** [comment] 2024-10-05 09:11
I quite like that it currently shows how much more than the daily goal I've practiced.

Maybe the presentation can be optimized, with a completed bar and "you already are xy% over your daily goal"=

**Comment by aradzie** [comment] 2024-10-07 16:09
It's by design. The daily goal is not a hard limit, but just a simple reminder. Maybe you feel like today you want to do twice the daily goal, that's ok. 

Maybe we should keep it as is, and close this issue?

**Closed** 2024-10-09 06:59 UTC
